# TCL File Generated by Component Editor 13.0sp1
# Mon Nov 24 12:23:57 CET 2025
# DO NOT MODIFY


# 
# ALARM_BELL "ALARM_BELL" v1.0
#  2025.11.24.12:23:57
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module ALARM_BELL
# 
set_module_property DESCRIPTION ""
set_module_property NAME ALARM_BELL
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "My Own IP Cores"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ALARM_BELL
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ALARM_BELL_avalon_interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file ALARM_BELL_avalon_interface.vhd VHDL PATH ../src/ALARM_BELL_avalon_interface.vhd TOP_LEVEL_FILE
add_fileset_file ALARM_BELL.vhd VHDL PATH ../src/ALARM_BELL.vhd
add_fileset_file CHENILLIARD.vhd VHDL PATH ../src/CHENILLIARD.vhd
add_fileset_file FDIV.vhd VHDL PATH ../src/FDIV.vhd


# 
# parameters
# 
add_parameter Fclock POSITIVE 50000000
set_parameter_property Fclock DEFAULT_VALUE 50000000
set_parameter_property Fclock DISPLAY_NAME Fclock
set_parameter_property Fclock TYPE POSITIVE
set_parameter_property Fclock UNITS None
set_parameter_property Fclock ALLOWED_RANGES 1:2147483647
set_parameter_property Fclock HDL_PARAMETER true
add_parameter FTick POSITIVE 1000
set_parameter_property FTick DEFAULT_VALUE 1000
set_parameter_property FTick DISPLAY_NAME FTick
set_parameter_property FTick TYPE POSITIVE
set_parameter_property FTick UNITS None
set_parameter_property FTick ALLOWED_RANGES 1:2147483647
set_parameter_property FTick HDL_PARAMETER true
add_parameter N POSITIVE 250
set_parameter_property N DEFAULT_VALUE 250
set_parameter_property N DISPLAY_NAME N
set_parameter_property N TYPE POSITIVE
set_parameter_property N UNITS None
set_parameter_property N ALLOWED_RANGES 1:2147483647
set_parameter_property N HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 chipselect chipselect Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 byteenable byteenable Input 4
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink clock clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink resetn reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock ""
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end Q_export export Output 32

